package ru.netology

fun main() {
    println("Добавление заметок")
    NoteService.add(Note(ownerId = 11))
    NoteService.add(Note(ownerId = 22))
    NoteService.add(Note(ownerId = 11))
    NoteService.add(Note(ownerId = 33))
    NoteService.printAll(NoteService.elements)
    println("")
    println("Добавление комментариев")
    CommentToNoteService.add(CommentToNote(noteId = 1, ownerId = 11))
    CommentToNoteService.add(CommentToNote(noteId = 2, ownerId = 22))
    CommentToNoteService.add(CommentToNote(noteId = 2, ownerId = 22))
    CommentToNoteService.add(CommentToNote(noteId = 3, ownerId = 33))
    CommentToNoteService.add(CommentToNote(noteId = 1, ownerId = 11))
    CommentToNoteService.printAll(CommentToNoteService.elements)
    println("")
    println("Список заметок по ownerId")
    NoteService.get(11)
    println("")
    println("Список комментариев к заметке по noteId")
    CommentToNoteService.getComments(1)
    println("")
    println("Редактирование заметки")
    println(NoteService.edit(Note(id = 4, ownerId = 33, title = "New title")))
    println("")
    println("Список заметок после редактирования")
    NoteService.printAll(NoteService.elements)
    println("")
    println("Редактирование комментария")
    println(CommentToNoteService.edit(CommentToNote(id = 5, noteId = 1, ownerId = 11, message = "New message")))
    println("")
    println("Список комментариев после редактирования")
    CommentToNoteService.printAll(CommentToNoteService.elements)
    println("")
    println("Удаление заметки c комментариями")
    println(NoteService.delete(Note(id = 2, ownerId = 22)))
    println("")
    println("Список заметок после удаления")
    NoteService.printAll(NoteService.elements)
    println("")
    println("Список комментариев после удаления")
    CommentToNoteService.printAll(CommentToNoteService.elements)
    println("")
    println("Поиск заметки по id")
    println(NoteService.findById(1))
    println("")
    println("Удаление комментария пo id")
    println(CommentToNoteService.delete(CommentToNote(id = 4, noteId = 3, ownerId = 33)))
    println("")
    println("Список комментариев после удаления")
    CommentToNoteService.printAll(CommentToNoteService.elements)
    println("")
    println("Список удаленных заметок")
    NoteService.printAll(NoteService.removedElements)
    println("")
    println("Список удаленных комментариев")
    CommentToNoteService.printAll(CommentToNoteService.removedElements)
    println("")
    println("Восстановление комментария")
    println(CommentToNoteService.restoreComment(CommentToNote(id = 4, noteId = 3, ownerId = 33)))
    println("")
    println("Список комментариев после восстановления")
    CommentToNoteService.printAll(CommentToNoteService.elements)
    println("")
    println("Список удаленных комментариев после восстановления")
    CommentToNoteService.printAll(CommentToNoteService.removedElements)
}